### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by Ruth-ikegah** [badging/documentation#1]
I'm Ruth Ikegah, a beginner in open source and technical writing. I will love to be a part of this documentation process when it kicks to start.

**Comment by mikeysan** [comment]
Could one of the maintainers please help us (issue creator and a humble observer) understand why this issue opened in July has no response at all when an issue openned later (August) has already been dealt with and closed? Some feedback, even if it is a "No", is always good. 

I ask because I was about to open a new issue and this concerns me as it doesn't reflect well on the team.

**Comment by germonprez** [comment]
Hi @mikeysan Thanks for the ping on this. 

I think this issue can be closed as @Ruth-ikegah has been instrumental in helping develop the D&I Badging program. Ruth is also one of the key Reviewers for the program as can be seen here: 

https://chaoss.community/diversity-and-inclusion-badging/

I will note that with respect to badging documentation, @xiaoya-Esther has been working as part of GSoD to build out the documentation. More information (and contributions) can be done via: https://handbook.chaoss.community/community-handbook/badging/overview

Thanks again!
